### ISSUE TITLE
"Pilot" and "Field medic" jobroles toggle their priority together,

### ISSUE THREAD

**Issue by Raeschen** [CHOMPStation2/CHOMPStation2#2189] opened 2021-06-13 07:44 UTC
![image](https://user-images.githubusercontent.com/30182250/121799354-e904d480-cc2b-11eb-8e7f-7ed5b41a0ac9.png)

As shown in image.
Valid at date of bugreport.

**Comment by Razgriz1032** [comment] 2021-06-13 09:47
Duplicate of https://github.com/CHOMPStation2/CHOMPStation2/issues/1676

**Closed by Razgriz1032** 2021-06-13 09:47 UTC
