### ISSUE TITLE
Low Walls can not be deconstructed, only violence sates them

### ISSUE THREAD

**Issue by VictorZisthus** [CHOMPStation2/CHOMPStation2#4451] opened 2022-06-30 00:59 UTC
#### Brief description of the bug
Title

#### What you expected to happen
Welder to remove the walls

#### What actually happened
Only the following works:
https://youtu.be/NOZONW-UK0w?t=26

#### Steps to reproduce
- Build Low Wall
- Try to Remove Low Wall
- Realise violence is the only answer

**Comment by xnqm8h** [comment] 2022-08-04 02:34
Might want to take a peek [here](https://github.com/CHOMPStation2/CHOMPStation2/blob/5d7a2a1f4e5f33e3307834f95ae53b0b7e1ece1a/code/game/objects/structures/low_wall.dm#L88-L102)

It looks like you are supposed to use a wrench and not a welder.

**Comment by VictorZisthus** [comment] 2022-08-05 00:59
> Might want to take a peek [here](https://github.com/CHOMPStation2/CHOMPStation2/blob/5d7a2a1f4e5f33e3307834f95ae53b0b7e1ece1a/code/game/objects/structures/low_wall.dm#L88-L102)
> 
> It looks like you are supposed to use a wrench and not a welder.

Odd, I thought I tried that. I'll make another effort tonight after I finish the cocoon bomb issue.

**Comment by xnqm8h** [comment] 2022-09-21 00:59
After testing I can confirm that using a wrench will deconstruct a low wall. Could you close this issue @VictorZisthus unless you believe there to still be an issue?

**Closed** 2022-09-21 01:03 UTC
