### ISSUE TITLE
Hack Multitool won't hack!

### ISSUE THREAD

**Issue by lowpowermia** [CHOMPStation2/CHOMPStation2#495] opened 2020-08-16 01:56 UTC
#### Brief description of the issue

The hacking multitool, accessible for traitor stuff doesn't hack like it used to. It doesn't slowly hack into the door. 
#### What you expected to happen
Touch multitool to door, hack slowly, open door, open a few doors, woo!

#### What actually happened
Touch Multitool to door. Stare. Touch multitool to door.
Be disappointed. Repeat.

#### Steps to reproduce
1. Obtain /obj/item/device/multitool/hacktool. 
2. Screwdriver hacktool.
3. Touch to nonmangled door attempting to be hacked.
4. Stare at door in longing.

#### Code Revision
https://github.com/CHOMPStation2/CHOMPStation2/blob/62551d7fda4bb9a9a867b4cb7104ef1b6fb22883/code/game/objects/items/devices/hacktool.dm
I don't know what the actual issue is, but I think it might be some debug stuff to look into.

**Comment by Shadow-Quill** [comment] 2020-08-16 04:36
Duplicate of https://github.com/PolarisSS13/Polaris/issues/6943

**Comment by ExabyteDiscord** [comment] 2021-09-06 23:26
This has since been fixed.

**Closed by ExabyteDiscord** 2021-09-06 23:26 UTC
Labels: Bug, Upstream Issue
